<a href="https://colab.research.google.com/github/ErfanEbFiN79/Erfan-Python/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [2]:
import torch

In [3]:
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors
Creating Tensors

Scalers are linear (or more precisely affine) transformers and differ from each other in the way they estimate the parameters used to shift and scale each feature. QuantileTransformer provides non-linear transformations in which distances between marginal outliers and inliers are shrunk.

PyTorch tensors are created usin torch.Tensor()

In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get tensor back as python int
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# Matrix
Matrix = torch.tensor([[7,8],[9,10]])
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
Matrix.ndim

2

In [12]:
Matrix.size()

torch.Size([2, 2])

In [13]:
Matrix.shape

torch.Size([2, 2])

In [14]:
type(Matrix)

torch.Tensor

In [15]:
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [16]:
Matrix[0]

tensor([7, 8])

In [17]:
Matrix[1]

tensor([ 9, 10])

In [18]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [19]:
TENSOR.ndim

3

In [20]:
TENSOR.shape

torch.Size([1, 3, 3])

In [21]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [22]:
TENSOR[0][0]

tensor([1, 2, 3])

In [23]:
TENSOR[0][2]

tensor([2, 4, 5])

In [24]:
TENSOR[0][1][1]

tensor(6)

In [25]:
MyTensorTest = torch.tensor([[[1,2,3],
                              [4,5,6],
                              [7,8,9]],
                             [[10,12,13],
                              [14,16,17],
                              [18,19,20]]])

In [26]:
MyTensorTest.shape

torch.Size([2, 3, 3])

In [27]:
MyTensorTest.ndim

3

In [28]:
MyTensorTest[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [29]:
MyTensorTest[1]

tensor([[10, 12, 13],
        [14, 16, 17],
        [18, 19, 20]])

In [30]:
# if we want to get a 16 from the Tesnor
MyTensorTest[1][1][1]

tensor(16)

### Random Tensor

We've established tensors represent some form of data.

And machine learning models such as neural networks manipulate and seek patterns within tensors.

But when building machine learning models with PyTorch, it's rare you'll create tensors by hand (like what we've been doing).

Instead, a machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

In essence:

'Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...'

As a data scientist, you can define how the machine learning model starts (initialization), looks at data (representation) and updates (optimization) its random numbers.

rand duc => https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [37]:
rand_tensor_1 = torch.rand(3)
rand_tensor_2 = torch.rand(3,4)
rand_tensor_3 = torch.rand(2,3,8)
print(f"{rand_tensor_1} has {rand_tensor_1.ndim} dimentions and the shape is {rand_tensor_1.shape} and type is {rand_tensor_1.dtype}\n")
print(f"{rand_tensor_2} has {rand_tensor_2.ndim} dimentions and the shape is {rand_tensor_2.shape} and type is {rand_tensor_2.dtype}\n")
print(f"{rand_tensor_3} has {rand_tensor_3.ndim} dimentions and the shape is {rand_tensor_3.shape} and type is {rand_tensor_3.dtype}\n")

tensor([0.9354, 0.2375, 0.9369]) has 1 dimentions and the shape is torch.Size([3]) and type is torch.float32

tensor([[0.9760, 0.6143, 0.3585, 0.4502],
        [0.0934, 0.3757, 0.1060, 0.3406],
        [0.2676, 0.5581, 0.0788, 0.6049]]) has 2 dimentions and the shape is torch.Size([3, 4]) and type is torch.float32

tensor([[[0.7767, 0.8968, 0.8341, 0.6979, 0.8283, 0.3958, 0.9370, 0.4509],
         [0.7115, 0.2560, 0.2899, 0.8967, 0.3080, 0.3006, 0.3182, 0.1235],
         [0.4146, 0.5727, 0.1664, 0.6760, 0.0788, 0.2935, 0.7156, 0.9449]],

        [[0.2936, 0.4970, 0.5070, 0.7363, 0.4751, 0.4002, 0.5992, 0.4527],
         [0.3644, 0.4188, 0.6878, 0.8928, 0.2433, 0.0892, 0.1174, 0.4250],
         [0.6548, 0.8882, 0.2687, 0.1421, 0.5625, 0.6358, 0.6870, 0.1426]]]) has 3 dimentions and the shape is torch.Size([2, 3, 8]) and type is torch.float32



The flexibility of torch.rand() is that we can adjust the size to be whatever we want.

For example, say you wanted a random tensor in the common image shape of [224, 224, 3] ([height, width, color_channels]).

In [41]:
random_image_tensor = torch.rand(size=(3,224,224))
print(f"Dimention = {random_image_tensor.ndim} and shape is {random_image_tensor.shape} => \n{random_image_tensor }")

Dimention = 3 and shape is torch.Size([3, 224, 224]) => 
tensor([[[0.6756, 0.7423, 0.0779,  ..., 0.7075, 0.3798, 0.2706],
         [0.4705, 0.0363, 0.0120,  ..., 0.4069, 0.7316, 0.0749],
         [0.7217, 0.7544, 0.2707,  ..., 0.3917, 0.2190, 0.2400],
         ...,
         [0.6357, 0.1664, 0.2428,  ..., 0.9632, 0.8047, 0.7087],
         [0.1959, 0.8935, 0.7032,  ..., 0.6428, 0.2738, 0.7325],
         [0.6541, 0.9489, 0.1560,  ..., 0.6763, 0.4974, 0.7144]],

        [[0.1544, 0.1426, 0.5191,  ..., 0.0727, 0.6117, 0.2139],
         [0.1047, 0.5916, 0.0271,  ..., 0.9873, 0.7638, 0.7111],
         [0.6043, 0.4323, 0.3425,  ..., 0.8886, 0.4302, 0.9231],
         ...,
         [0.9071, 0.0158, 0.4206,  ..., 0.2727, 0.9518, 0.7811],
         [0.3144, 0.1407, 0.8550,  ..., 0.9771, 0.0350, 0.9036],
         [0.0727, 0.8785, 0.5835,  ..., 0.4022, 0.7063, 0.1168]],

        [[0.9050, 0.8577, 0.1466,  ..., 0.9255, 0.8819, 0.7155],
         [0.7647, 0.5482, 0.9264,  ..., 0.1216, 0.0665, 0.0489],
 

In [50]:
# HandWriting at 16 * 16 black and white
# black < 0.5 / white >= 0
rand_handwriting_00 = torch.rand(2,16,16)
rand_handwriting_00

tensor([[[0.6747, 0.1496, 0.1915, 0.3546, 0.1105, 0.6214, 0.4420, 0.9827,
          0.1932, 0.0883, 0.6006, 0.3023, 0.9379, 0.0710, 0.1979, 0.4766],
         [0.4845, 0.1841, 0.2041, 0.9850, 0.6522, 0.1374, 0.7474, 0.7610,
          0.0244, 0.7327, 0.2116, 0.1582, 0.9333, 0.7847, 0.0640, 0.3236],
         [0.6422, 0.5634, 0.9760, 0.9408, 0.5779, 0.2646, 0.3795, 0.7348,
          0.3005, 0.4244, 0.8051, 0.7405, 0.4030, 0.2408, 0.8036, 0.2297],
         [0.4016, 0.3823, 0.9325, 0.3672, 0.4749, 0.4216, 0.2075, 0.5193,
          0.3099, 0.6714, 0.3162, 0.2409, 0.5774, 0.9413, 0.2537, 0.9977],
         [0.3922, 0.5720, 0.1606, 0.0649, 0.9342, 0.0834, 0.8876, 0.5257,
          0.1118, 0.2282, 0.8735, 0.8202, 0.9052, 0.1153, 0.1434, 0.0365],
         [0.5079, 0.7506, 0.5653, 0.0749, 0.5964, 0.0912, 0.8646, 0.9890,
          0.4580, 0.9950, 0.7449, 0.4640, 0.5131, 0.9838, 0.3195, 0.6647],
         [0.1464, 0.0947, 0.7784, 0.5048, 0.8985, 0.9953, 0.1351, 0.4164,
          0.6051, 0.9266, 0.1184