<a href="https://colab.research.google.com/github/ErfanEbFiN79/Erfan-Python/blob/main/Python%20Erfan/PyTorch/Colab/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [2]:
import torch

In [3]:
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors
Creating Tensors

Scalers are linear (or more precisely affine) transformers and differ from each other in the way they estimate the parameters used to shift and scale each feature. QuantileTransformer provides non-linear transformations in which distances between marginal outliers and inliers are shrunk.

PyTorch tensors are created usin torch.Tensor()

In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get tensor back as python int
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# Matrix
Matrix = torch.tensor([[7,8],[9,10]])
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
Matrix.ndim

2

In [12]:
Matrix.size()

torch.Size([2, 2])

In [13]:
Matrix.shape

torch.Size([2, 2])

In [14]:
type(Matrix)

torch.Tensor

In [15]:
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [16]:
Matrix[0]

tensor([7, 8])

In [17]:
Matrix[1]

tensor([ 9, 10])

In [18]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [19]:
TENSOR.ndim

3

In [20]:
TENSOR.shape

torch.Size([1, 3, 3])

In [21]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [22]:
TENSOR[0][0]

tensor([1, 2, 3])

In [23]:
TENSOR[0][2]

tensor([2, 4, 5])

In [24]:
TENSOR[0][1][1]

tensor(6)

In [25]:
MyTensorTest = torch.tensor([[[1,2,3],
                              [4,5,6],
                              [7,8,9]],
                             [[10,12,13],
                              [14,16,17],
                              [18,19,20]]])

In [26]:
MyTensorTest.shape

torch.Size([2, 3, 3])

In [27]:
MyTensorTest.ndim

3

In [28]:
MyTensorTest[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [29]:
MyTensorTest[1]

tensor([[10, 12, 13],
        [14, 16, 17],
        [18, 19, 20]])

In [30]:
# if we want to get a 16 from the Tesnor
MyTensorTest[1][1][1]

tensor(16)

### Random Tensor

We've established tensors represent some form of data.

And machine learning models such as neural networks manipulate and seek patterns within tensors.

But when building machine learning models with PyTorch, it's rare you'll create tensors by hand (like what we've been doing).

Instead, a machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

In essence:

'Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...'

As a data scientist, you can define how the machine learning model starts (initialization), looks at data (representation) and updates (optimization) its random numbers.

rand duc => https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [31]:
rand_tensor_1 = torch.rand(3)
rand_tensor_2 = torch.rand(3,4)
rand_tensor_3 = torch.rand(2,3,8)
print(f"{rand_tensor_1} has {rand_tensor_1.ndim} dimentions and the shape is {rand_tensor_1.shape} and type is {rand_tensor_1.dtype}\n")
print(f"{rand_tensor_2} has {rand_tensor_2.ndim} dimentions and the shape is {rand_tensor_2.shape} and type is {rand_tensor_2.dtype}\n")
print(f"{rand_tensor_3} has {rand_tensor_3.ndim} dimentions and the shape is {rand_tensor_3.shape} and type is {rand_tensor_3.dtype}\n")

tensor([0.0951, 0.7412, 0.8418]) has 1 dimentions and the shape is torch.Size([3]) and type is torch.float32

tensor([[0.9001, 0.5569, 0.5112, 0.2233],
        [0.8333, 0.9673, 0.5748, 0.8748],
        [0.2001, 0.1422, 0.6660, 0.8943]]) has 2 dimentions and the shape is torch.Size([3, 4]) and type is torch.float32

tensor([[[0.9633, 0.4110, 0.3451, 0.7725, 0.9570, 0.1650, 0.1854, 0.3282],
         [0.4592, 0.2879, 0.3140, 0.8803, 0.2668, 0.1711, 0.8177, 0.4443],
         [0.7215, 0.6541, 0.9999, 0.4543, 0.3655, 0.5992, 0.8365, 0.1841]],

        [[0.9223, 0.0558, 0.9556, 0.7690, 0.8632, 0.1788, 0.3314, 0.7575],
         [0.6354, 0.4151, 0.7383, 0.2850, 0.5404, 0.7865, 0.0018, 0.7662],
         [0.8097, 0.7937, 0.1876, 0.2399, 0.8259, 0.1673, 0.4435, 0.2074]]]) has 3 dimentions and the shape is torch.Size([2, 3, 8]) and type is torch.float32



The flexibility of torch.rand() is that we can adjust the size to be whatever we want.

For example, say you wanted a random tensor in the common image shape of [224, 224, 3] ([height, width, color_channels]).

In [32]:
random_image_tensor = torch.rand(size=(3,224,224))
print(f"Dimention = {random_image_tensor.ndim} and shape is {random_image_tensor.shape} => \n{random_image_tensor }")

Dimention = 3 and shape is torch.Size([3, 224, 224]) => 
tensor([[[0.9061, 0.6196, 0.9129,  ..., 0.5226, 0.0164, 0.8103],
         [0.5545, 0.2914, 0.6995,  ..., 0.8872, 0.4917, 0.3593],
         [0.8712, 0.6582, 0.7108,  ..., 0.7949, 0.3697, 0.7056],
         ...,
         [0.6420, 0.4133, 0.3005,  ..., 0.5495, 0.7427, 0.3865],
         [0.6017, 0.3666, 0.9554,  ..., 0.5505, 0.4415, 0.9640],
         [0.8784, 0.6318, 0.2343,  ..., 0.5779, 0.9552, 0.0105]],

        [[0.1321, 0.7054, 0.3443,  ..., 0.4631, 0.6960, 0.4061],
         [0.9985, 0.4354, 0.7123,  ..., 0.2681, 0.2841, 0.8760],
         [0.9862, 0.2224, 0.8063,  ..., 0.7292, 0.7125, 0.1274],
         ...,
         [0.2294, 0.3907, 0.5130,  ..., 0.1016, 0.8064, 0.7135],
         [0.6497, 0.0462, 0.4506,  ..., 0.6147, 0.4693, 0.4247],
         [0.5254, 0.7081, 0.9178,  ..., 0.8559, 0.2226, 0.0903]],

        [[0.3256, 0.8160, 0.9418,  ..., 0.1518, 0.2934, 0.4942],
         [0.8395, 0.3435, 0.4900,  ..., 0.3630, 0.2147, 0.6767],
 

In [33]:
# HandWriting at 16 * 16 black and white
# black < 0.5 / white >= 0
rand_handwriting_00 = torch.rand(2,16,16)
rand_handwriting_00

tensor([[[0.2950, 0.1176, 0.8356, 0.4374, 0.4444, 0.7633, 0.9191, 0.5458,
          0.8294, 0.7895, 0.2053, 0.3315, 0.8483, 0.7174, 0.9689, 0.4652],
         [0.9371, 0.1720, 0.3215, 0.6977, 0.9178, 0.2614, 0.7809, 0.2955,
          0.5672, 0.6631, 0.8643, 0.8922, 0.3387, 0.5234, 0.2217, 0.0453],
         [0.9643, 0.0422, 0.5192, 0.4531, 0.8583, 0.5631, 0.8452, 0.5428,
          0.0236, 0.1704, 0.3700, 0.5231, 0.8011, 0.1022, 0.5833, 0.1356],
         [0.1833, 0.8136, 0.2014, 0.6580, 0.8219, 0.4453, 0.9343, 0.3506,
          0.1874, 0.4252, 0.6607, 0.9585, 0.4216, 0.2690, 0.8446, 0.0929],
         [0.9698, 0.9223, 0.9737, 0.8372, 0.2938, 0.7425, 0.6061, 0.4153,
          0.9909, 0.5280, 0.8866, 0.1266, 0.4440, 0.7285, 0.2332, 0.7811],
         [0.3050, 0.2162, 0.7818, 0.9867, 0.4754, 0.4680, 0.0260, 0.5628,
          0.1900, 0.2750, 0.0031, 0.5745, 0.3426, 0.3697, 0.1031, 0.9913],
         [0.6477, 0.8065, 0.9972, 0.7389, 0.1069, 0.1974, 0.9303, 0.9689,
          0.6175, 0.2309, 0.5650

## Zeros and ones

Sometimes you'll just want to fill tensors with zeros or ones.

This happens a lot with masking (like masking some of the values in one tensor with zeros to let a model know not to learn them).

In [34]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,3))
print(f"Structure -> \n{zeros}\nType : {zeros.dtype}")

Structure -> 
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
Type : torch.float32


In [35]:
# Create a tensor of all one
ones = torch.ones(size=(3,4))
print(f"Structure -> \n{ones}\nType : {ones.dtype}")

Structure -> 
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
Type : torch.float32


##Creating a range and tensors like
Sometimes you might want a range of numbers, such as 1 to 10 or 0 to 100.

You can use torch.arange(start, end, step) to do so.

Where:

* start = start of range (e.g. 0)
* end = end of range (e.g. 10)
* step = how many steps in between each value (e.g. 1)

In [36]:
# 1 until 20 just odd
Xodd = torch.arange(1,20,2)
Xodd

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [37]:
# 1 until 20 just even
Xeven = torch.arange(2,21,2)
Xeven

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [38]:
XFive = torch.arange(0,51,5)
XFive

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])


Sometimes you might want one tensor of a certain type with the same shape as another tensor.

For example, a tensor of all zeros with the same shape as a previous tensor.

To do so you can use torch.zeros_like(input) or torch.ones_like(input) which return a tensor filled with zeros or ones in the same shape as the input respectively.

In [39]:
XFive.shape

torch.Size([11])

In [40]:
X_Shape_Copy1 = torch.zeros_like(input=XFive)
X_Shape_Copy1, X_Shape_Copy1.shape, X_Shape_Copy1.dtype

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), torch.Size([11]), torch.int64)

In [41]:
X_Shape_Copy2 = torch.ones_like(X_Shape_Copy1)
X_Shape_Copy2, X_Shape_Copy2.shape, X_Shape_Copy2.dtype

(tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]), torch.Size([11]), torch.int64)


##Tensor datatypes
There are many different tensor datatypes available in PyTorch.
link: https://docs.pytorch.org/docs/stable/tensors.html#data-types

Some are specific for CPU and some are better for GPU.

Getting to know which one can take some time.

Generally if you see torch.cuda anywhere, the tensor is being used for GPU (since Nvidia GPUs use a computing toolkit called CUDA).

The most common type (and generally the default) is torch.float32 or torch.float.

This is referred to as "32-bit floating point".

But there's also 16-bit floating point (torch.float16 or torch.half) and 64-bit floating point (torch.float64 or torch.double).

And to confuse things even more there's also 8-bit, 16-bit, 32-bit and 64-bit integers.

Plus more!

Note: An integer is a flat round number like 7 whereas a float has a decimal 7.0.

The reason for all of these is to do with precision in computing.

Precision is the amount of detail used to describe a number.

The higher the precision value (8, 16, 32), the more detail and hence data used to express a number.

This matters in deep learning and numerical computing because you're making so many operations, the more detail you have to calculate on, the more compute you have to use.

So lower precision datatypes are generally faster to compute on but sacrifice some performance on evaluation metrics like accuracy (faster to compute but less accurate).

Resources:
https://docs.pytorch.org/docs/stable/tensors.html#data-types

https://en.wikipedia.org/wiki/Precision_(computer_science)

See the PyTorch documentation for a list of all available tensor datatypes.
Read the Wikipedia page for an overview of what precision in computing) is.
Let's see how to create some tensors with specific datatypes. We can do so using the dtype paramete

In [42]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))


Aside from shape issues (tensor shapes don't match up), two of the other most common issues you'll come across in PyTorch are datatype and device issues.

For example, one of tensors is torch.float32 and the other is torch.float16 (PyTorch often likes tensors to be the same format).

Or one of your tensors is on the CPU and the other is on the GPU (PyTorch likes calculations between tensors to be on the same device).

We'll see more of this device talk later on.

For now let's create a tensor with dtype=torch.float16.

In [43]:
float_32_tensor.dtype

torch.float32

In [44]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [45]:
float_16_tensor2 = float_32_tensor.type(torch.float16)
float_16_tensor2

tensor([3., 6., 9.], dtype=torch.float16)

In [46]:
# WOW, We can do this
float_32_tensor * float_16_tensor
# but try to use same data type, ok??
# because: maby get error at large database

tensor([ 9., 36., 81.])

In [47]:
float_16_mulb_32 = float_32_tensor * float_16_tensor
float_16_mulb_32.dtype

torch.float32

In [48]:
int_32_tensor = torch.tensor([1,2,3], dtype=torch.int32)
int_32_tensor

tensor([1, 2, 3], dtype=torch.int32)

In [49]:
(float_32_tensor * int_32_tensor).dtype
# Wow it's work too :/

torch.float32

### Getting information from tensors
Once you've created tensors (or someone else or a PyTorch module has created them for you), you might want to get some information from them.

We've seen these before but three of the most common attributes you'll want to find out about tensors are:

1. shape - what shape is the tensor? (some operations require specific shape rules)
2. dtype - what datatype are the elements within the tensor stored in?
3. device - what device is the tensor stored on? (usually GPU or CPU)

Let's create a random tensor and find out details about it.

In [50]:
# Create a tensor
exTensor1 = torch.arange(0,11,2)
exTensor1

tensor([ 0,  2,  4,  6,  8, 10])

In [51]:
# Find out details about <exTensor1>
print(exTensor1)
print(f"Datatype of tensor: {exTensor1.dtype}")
print(f"Shape of tensor: {exTensor1.shape}")
print(f"Dimenstion of tensor: {exTensor1.ndim}")
print(f"Device tensor is on: {exTensor1.device}")

tensor([ 0,  2,  4,  6,  8, 10])
Datatype of tensor: torch.int64
Shape of tensor: torch.Size([6])
Dimenstion of tensor: 1
Device tensor is on: cpu


In [52]:
print(XFive)
print(f"Shape : {XFive.shape}")
print(f"Data type : {XFive.dtype}")
print(f"Dimenstion : {XFive.ndim}")
print(f"Device : {XFive.device}")

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])
Shape : torch.Size([11])
Data type : torch.int64
Dimenstion : 1
Device : cpu


## Manipulating tensors (tensor operations)

Manipulating tensors (tensor operations)¶
In deep learning, data (images, text, video, audio, protein structures, etc) gets represented as tensors.

A model learns by investigating those tensors and performing a series of operations (could be 1,000,000s+) on tensors to create a representation of the patterns in the input data.

These operations are often a wonderful dance between:

* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication
And that's it. Sure there are a few more here and there but these are the basic building blocks of neural networks.

Stacking these building blocks in the right way, you can create the most sophisticated of neural networks (just like lego!).

In [53]:
exTensor1

tensor([ 0,  2,  4,  6,  8, 10])

In [54]:
# Let's + 10 to the each of the elements
exTensor1 + 10

tensor([10, 12, 14, 16, 18, 20])

In [55]:
# Lets try *
%%time
exTensor1 * 10

CPU times: user 709 µs, sys: 0 ns, total: 709 µs
Wall time: 1.52 ms


tensor([  0,  20,  40,  60,  80, 100])

In [56]:
%%time
torch.multiply(exTensor1, 10)

CPU times: user 241 µs, sys: 39 µs, total: 280 µs
Wall time: 2.32 ms


tensor([  0,  20,  40,  60,  80, 100])

In [57]:
# When you dont use = that means you don't change
#    the origin value, just you see a results
exTensor1

tensor([ 0,  2,  4,  6,  8, 10])

PyTorch also has a bunch of built-in functions like torch.mul() (short for multiplication) and torch.add() to perform basic operations.

In [58]:
# Insted of * we can us multiply funation
torch.multiply(exTensor1, 10)

tensor([  0,  20,  40,  60,  80, 100])

In [59]:
# Insted of + we can us add function
print(torch.add(exTensor1, 10))
print(torch.add(exTensor1, exTensor1))

tensor([10, 12, 14, 16, 18, 20])
tensor([ 0,  4,  8, 12, 16, 20])


! However, it's more common to use the operator symbols like * instead of torch.mul()


## Matrix multiplication (is all you need)
One of the most common operations in machine learning and deep learning algorithms (like neural networks) is matrix multiplication.


PyTorch implements matrix multiplication functionality in the torch.matmul() method.

The main two rules for matrix multiplication to remember are:

1. The **inner dimensions** must match:
* (3, 2) @ (3, 2) won't work
* (2, 3) @ (3, 2) will work
* (3, 2) @ (2, 3) will work
The resulting matrix has the shape of
2. the **outer dimensions**:
* '(2, 3) @ (3, 2)' -> '(2, 2)'
* '(3, 2) @ (2, 3)' -> '(3, 3)'

Note: "@" in Python is the symbol for matrix multiplication.

Resource: You can see all of the rules for matrix multiplication using torch.matmul() in the PyTorch documentation.

In [60]:
exTensor1

tensor([ 0,  2,  4,  6,  8, 10])

In [61]:
torch.matmul(exTensor1, exTensor1)

tensor(220)

In [62]:
exTensor1 @ exTensor1

tensor(220)


You can do matrix multiplication by hand but it's not recommended.

The in-built torch.matmul() method is faster.

In [63]:
exTensor2_1 = torch.tensor([[1,2],
                           [3,4],
                           [5,6]])

exTensor2_2 = torch.tensor([[7,10],
                             [8,11],
                             [9,12]])


## One of the most common errors in deep learning (shape errors)
Because much of deep learning is multiplying and performing operations on matrices and matrices have a strict rule about what shapes and sizes can be combined, one of the most common errors you'll run into in deep learning is shape mismatches.

In [64]:
exTensor2_1.shape

torch.Size([3, 2])

In [65]:
exTensor2_2.shape

torch.Size([3, 2])

we can do matrix multiplication becase it's broke role one
for exTensor2_1 and exTensor2_2
**we need transpose one of them**

One of the ways to do this is with a transpose (switch the dimensions of a given tensor).

You can perform transposes in PyTorch using either:

* torch.transpose(input, dim0, dim1) - where input is the desired tensor to transpose and dim0 and dim1 are the dimensions to be swapped.
* tensor.T - where tensor is the desired tensor to transpose.

In [66]:
print(exTensor2_1)
print("\n")
print(exTensor2_2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])


In [67]:
print(exTensor2_1)
print("\n")
print(exTensor2_2.T)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


tensor([[ 7,  8,  9],
        [10, 11, 12]])


In [68]:
exTensor2_2_New = exTensor2_2.T

In [69]:
# The operation works when tensor_B is transposed
print(f"Original shapes: exTensor2_1 = {exTensor2_1.shape}, exTensor2_2= {exTensor2_2.shape}\n")
print(f"New shapes: exTensor2_1 = {exTensor2_1.shape} (same as above), exTensor2_2 = {exTensor2_2.T.shape}\n")
print(f"Multiplying: {exTensor2_1.shape} * {exTensor2_2.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(exTensor2_1, exTensor2_2.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: exTensor2_1 = torch.Size([3, 2]), exTensor2_2= torch.Size([3, 2])

New shapes: exTensor2_1 = torch.Size([3, 2]) (same as above), exTensor2_2 = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


Without the transpose, the rules of matrix multiplication aren't fulfilled and we get an error like above.

How about a visual?

![visual demo of matrix multiplication](https://github.com/mrdbourke/pytorch-deep-learning/raw/main/images/00-matrix-multiply-crop.gif)

You can create your own matrix multiplication visuals like this at http://matrixmultiplication.xyz/.

> **Note:** A matrix multiplication like this is also referred to as the [**dot product**](https://www.mathsisfun.com/algebra/vectors-dot-product.html) of two matrices.



Neural networks are full of matrix multiplications and dot products.

The [`torch.nn.Linear()`](https://pytorch.org/docs/1.9.1/generated/torch.nn.Linear.html) module (we'll see this in action later on), also known as a feed-forward layer or fully connected layer, implements a matrix multiplication between an input `x` and a weights matrix `A`.

$$
y = x\cdot{A^T} + b
$$

Where:
* `x` is the input to the layer (deep learning is a stack of layers like `torch.nn.Linear()` and others on top of each other).
* `A` is the weights matrix created by the layer, this starts out as random numbers that get adjusted as a neural network learns to better represent patterns in the data (notice the "`T`", that's because the weights matrix gets transposed).
  * **Note:** You might also often see `W` or another letter like `X` used to showcase the weights matrix.
* `b` is the bias term used to slightly offset the weights and inputs.
* `y` is the output (a manipulation of the input in the hopes to discover patterns in it).

This is a linear function (you may have seen something like $y = mx+b$ in high school or elsewhere), and can be used to draw a straight line!

Let's play around with a linear layer.

Try changing the values of `in_features` and `out_features` below and see what happens.

Do you notice anything to do with the shapes?

In [70]:
exTensor2_1, exTensor2_1.shape

(tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 torch.Size([3, 2]))

In [71]:
exTensor2_2_New, exTensor2_2_New.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [72]:
exTensorR1 = exTensor2_1 @ exTensor2_2_New

In [73]:
print(exTensorR1)
print(f"Shape : {exTensorR1.shape}")
print(f"Dimenstion : {exTensorR1.ndim}")
print(f"Datatype : {exTensorR1.dtype}")
print(f"Device : {exTensorR1.device}")

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
Shape : torch.Size([3, 3])
Dimenstion : 2
Datatype : torch.int64
Device : cpu



## Finding the min, max, mean, sum, etc (aggregation)
Now we've seen a few ways to manipulate tensors, let's run through a few ways to aggregate them (go from more values to less values).

In [74]:
exTensorR1

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [75]:
#Find Min
exTensorR1.min()

tensor(27)

In [76]:
#Find Max
exTensorR1.max()

tensor(117)

In [77]:
#Find mean
exTensorR1.type(torch.float32).mean()

tensor(68.)

> **Note:** You may find some methods such as `torch.mean()` require tensors to be in `torch.float32` (the most common) or another specific datatype, otherwise the operation will fail.



In [78]:
# Sum of elements
exTensorR1.sum()

tensor(612)

You can also do the same as above with `torch` methods.

In [79]:
torch.min(exTensorR1), torch.max(exTensorR1)

(tensor(27), tensor(117))

In [80]:
torch.mean(exTensorR1.type(torch.float32)), torch.sum(exTensorR1)

(tensor(68.), tensor(612))

## Finding position of min and max value

This is helpful incase you just want the position where the highest (or lowest) value is and not the actual value itself (we'll see this in a later section when using the [softmax activation function](https://pytorch.org/docs/stable/generated/torch.nn.Softmax.html)).

In [81]:
import random

In [82]:
def BackRandom():
  return random.randint(1, 50)

In [83]:
exTensor2 = torch.tensor([BackRandom(),BackRandom(),BackRandom()])

In [84]:
exTensor2.argmax()

tensor(0)

In [85]:
exTensor2.argmin()

tensor(1)

In [86]:
exTensor2[2]

tensor(36)

In [87]:
exTensor2[1]

tensor(20)

In [88]:
exTensor2

tensor([43, 20, 36])

In [89]:
exTensor3 = torch.arange(BackRandom(), BackRandom())

In [90]:
exTensor3.argmax()

tensor(15)

In [91]:
exTensor3.argmin()

tensor(0)

In [92]:
exTensor3

tensor([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

### Reshaping, stacking, squeezing and unsqueezing

Often times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them.

To do so, some popular methods are:

| Method | One-line description |
| ----- | ----- |
| [`torch.reshape(input, shape)`](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape) | Reshapes `input` to `shape` (if compatible), can also use `torch.Tensor.reshape()`. |
| [`Tensor.view(shape)`](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html) | Returns a view of the original tensor in a different `shape` but shares the same data as the original tensor. |
| [`torch.stack(tensors, dim=0)`](https://pytorch.org/docs/1.9.1/generated/torch.stack.html) | Concatenates a sequence of `tensors` along a new dimension (`dim`), all `tensors` must be same size. |
| [`torch.squeeze(input)`](https://pytorch.org/docs/stable/generated/torch.squeeze.html) | Squeezes `input` to remove all the dimenions with value `1`. |
| [`torch.unsqueeze(input, dim)`](https://pytorch.org/docs/1.9.1/generated/torch.unsqueeze.html) | Returns `input` with a dimension value of `1` added at `dim`. |
| [`torch.permute(input, dims)`](https://pytorch.org/docs/stable/generated/torch.permute.html) | Returns a *view* of the original `input` with its dimensions permuted (rearranged) to `dims`. |

Why do any of these?

Because deep learning models (neural networks) are all about manipulating tensors in some way. And because of the rules of matrix multiplication, if you've got shape mismatches, you'll run into errors. These methods help you make sure the right elements of your tensors are mixing with the right elements of other tensors.

Let's try them out.

In [93]:
exTensor4 = torch.arange(1., 10.)

In [94]:
exTensor4, exTensor4.shape, exTensor4.ndim

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), 1)

Now let's add an extra dimension with `torch.reshape()`.

In [95]:
# Add tree extra dimension
exTensor4.reshape(3,3), exTensor4.shape, exTensor4.ndim

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([9]),
 1)

In [96]:
# Add an extra dimension
exTensor4.reshape(1,9), exTensor4.shape, exTensor4.ndim

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([9]), 1)

We can also change the view with `torch.view()`.

In [97]:
exTensor4

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [98]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
exTensorR2 = exTensor4.view(3,3)
print(f"exTensorR2 shape: {exTensorR2.shape} / exTensor4 shape: {exTensor4.shape}")


exTensorR2 shape: torch.Size([3, 3]) / exTensor4 shape: torch.Size([9])


Remember though, changing the view of a tensor with `torch.view()` really only creates a new view of the *same* tensor.

So changing the view changes the original tensor too.

In [99]:
# changing exTensorR2 alose change exTensor4
exTensorR2[:, 0] = 5
exTensorR2, exTensor4

(tensor([[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]),
 tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]))

If we wanted to stack our new tensor on top of itself five times, we could do so with `torch.stack()`.

> NOTE: After this note `x` means **tensor**

In [100]:
x_stacked1 = torch.stack([exTensor4,exTensor4], dim=0)
x_stacked1

tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.]])

In [101]:
x_stacked1 = torch.stack([exTensor4,exTensor4], dim=1)
x_stacked1

tensor([[5., 5.],
        [2., 2.],
        [3., 3.],
        [5., 5.],
        [5., 5.],
        [6., 6.],
        [5., 5.],
        [8., 8.],
        [9., 9.]])

How about removing all single dimensions from a tensor?

To do so you can use `torch.squeeze()` (I remember this as *squeezing* the tensor to only have dimensions over 1).

In [117]:
#Create a tensor
exX4 = torch.arange(1., 8.)
exX4 = exX4.reshape(1,7)
print(f"Previous tensor: {exX4}")
print(f"Previous shape: {exX4.shape}")

# Remove extra dimension from x_reshaped
exX4 = exX4.squeeze()
print(f"\nNew tensor: {exX4}")
print(f"New shape: {exX4.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [118]:
# Tensor with multiple dimensions of size 1
x = torch.randn(3, 1, 4, 1, 5)
print(f"Original tensor shape: {x.shape}")

# Squeeze all dimensions of size 1
y = torch.squeeze(x)
print(f"Squeezed tensor shape (all): {y.shape}")

# Squeeze a specific dimension (if its size is 1)
z = torch.squeeze(x, dim=1) # Squeezes the second dimension (index 1)
print(f"Squeezed tensor shape (dim=1): {z.shape}")

w = torch.squeeze(x, dim=0) # Does not squeeze, as dim 0 has size 3
print(f"Squeezed tensor shape (dim=0): {w.shape}")

Original tensor shape: torch.Size([3, 1, 4, 1, 5])
Squeezed tensor shape (all): torch.Size([3, 4, 5])
Squeezed tensor shape (dim=1): torch.Size([3, 4, 1, 5])
Squeezed tensor shape (dim=0): torch.Size([3, 1, 4, 1, 5])


And to do the reverse of `torch.squeeze()` you can use `torch.unsqueeze()` to add a dimension value of 1 at a specific index.

In [119]:
print(f"\nNew tensor: {exX4}")
print(f"New shape: {exX4.shape}")
## Add an extra dimension with unsqueeze

exX4 = exX4.unsqueeze(dim=0)
print(f"\nNew tensor: {exX4}")
print(f"New shape: {exX4.shape}")


New tensor: tensor([1., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


You can also rearrange the order of axes values with `torch.permute(input, dims)`, where the `input` gets turned into a *view* with new `dims`.

In [126]:
# Create tensor with specific shape
x_image1 = torch.rand(size=(224,224,3)) #size => 0, size => 1, rgb => 2


x_image_permuted = x_image1.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_image1.shape}")
print(f"New shape: {x_image_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [138]:
# Think we save a data for a system like that
# system code:
# code => 0
# code_Key => 1
# key => 2
# key_load => 3
x_Code = torch.rand(size = (10,9,5,6))
print(f"x_Home1_Shape: {x_Code.shape}")
x_Code1_permuted = x_Code.permute(3,2,1,0)
print(f"x_Code1_permuted: {x_Code1_permuted.shape}")

x_Home1_Shape: torch.Size([10, 9, 5, 6])
x_Code1_permuted: torch.Size([6, 5, 9, 10])
