<a href="https://colab.research.google.com/github/ErfanEbFiN79/Erfan-Python/blob/main/Python%2520Erfan/PyTotch/Colab/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [3]:
import torch

In [4]:
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors
Creating Tensors

Scalers are linear (or more precisely affine) transformers and differ from each other in the way they estimate the parameters used to shift and scale each feature. QuantileTransformer provides non-linear transformations in which distances between marginal outliers and inliers are shrunk.

PyTorch tensors are created usin torch.Tensor()

In [5]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
# Get tensor back as python int
scalar.item()

7

In [8]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# Matrix
Matrix = torch.tensor([[7,8],[9,10]])
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
Matrix.ndim

2

In [13]:
Matrix.size()

torch.Size([2, 2])

In [14]:
Matrix.shape

torch.Size([2, 2])

In [15]:
type(Matrix)

torch.Tensor

In [16]:
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [17]:
Matrix[0]

tensor([7, 8])

In [18]:
Matrix[1]

tensor([ 9, 10])

In [19]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [20]:
TENSOR.ndim

3

In [21]:
TENSOR.shape

torch.Size([1, 3, 3])

In [22]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [23]:
TENSOR[0][0]

tensor([1, 2, 3])

In [24]:
TENSOR[0][2]

tensor([2, 4, 5])

In [25]:
TENSOR[0][1][1]

tensor(6)

In [26]:
MyTensorTest = torch.tensor([[[1,2,3],
                              [4,5,6],
                              [7,8,9]],
                             [[10,12,13],
                              [14,16,17],
                              [18,19,20]]])

In [27]:
MyTensorTest.shape

torch.Size([2, 3, 3])

In [28]:
MyTensorTest.ndim

3

In [29]:
MyTensorTest[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [30]:
MyTensorTest[1]

tensor([[10, 12, 13],
        [14, 16, 17],
        [18, 19, 20]])

In [31]:
# if we want to get a 16 from the Tesnor
MyTensorTest[1][1][1]

tensor(16)

### Random Tensor

We've established tensors represent some form of data.

And machine learning models such as neural networks manipulate and seek patterns within tensors.

But when building machine learning models with PyTorch, it's rare you'll create tensors by hand (like what we've been doing).

Instead, a machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

In essence:

'Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...'

As a data scientist, you can define how the machine learning model starts (initialization), looks at data (representation) and updates (optimization) its random numbers.

rand duc => https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [32]:
rand_tensor_1 = torch.rand(3)
rand_tensor_2 = torch.rand(3,4)
rand_tensor_3 = torch.rand(2,3,8)
print(f"{rand_tensor_1} has {rand_tensor_1.ndim} dimentions and the shape is {rand_tensor_1.shape} and type is {rand_tensor_1.dtype}\n")
print(f"{rand_tensor_2} has {rand_tensor_2.ndim} dimentions and the shape is {rand_tensor_2.shape} and type is {rand_tensor_2.dtype}\n")
print(f"{rand_tensor_3} has {rand_tensor_3.ndim} dimentions and the shape is {rand_tensor_3.shape} and type is {rand_tensor_3.dtype}\n")

tensor([0.5440, 0.1324, 0.6712]) has 1 dimentions and the shape is torch.Size([3]) and type is torch.float32

tensor([[0.0489, 0.6642, 0.7755, 0.9267],
        [0.0554, 0.6437, 0.6184, 0.1342],
        [0.6258, 0.1232, 0.3948, 0.2431]]) has 2 dimentions and the shape is torch.Size([3, 4]) and type is torch.float32

tensor([[[0.6283, 0.1572, 0.4555, 0.0088, 0.0865, 0.6468, 0.6766, 0.2271],
         [0.0632, 0.1755, 0.9815, 0.6480, 0.0182, 0.6377, 0.2645, 0.3695],
         [0.0830, 0.0196, 0.7395, 0.5238, 0.2815, 0.4425, 0.9154, 0.0701]],

        [[0.2791, 0.7655, 0.2177, 0.9177, 0.1289, 0.8563, 0.9136, 0.4559],
         [0.8837, 0.4079, 0.8916, 0.9947, 0.9041, 0.3798, 0.2402, 0.2451],
         [0.3371, 0.1125, 0.5468, 0.1463, 0.2515, 0.6685, 0.3314, 0.7513]]]) has 3 dimentions and the shape is torch.Size([2, 3, 8]) and type is torch.float32



The flexibility of torch.rand() is that we can adjust the size to be whatever we want.

For example, say you wanted a random tensor in the common image shape of [224, 224, 3] ([height, width, color_channels]).

In [33]:
random_image_tensor = torch.rand(size=(3,224,224))
print(f"Dimention = {random_image_tensor.ndim} and shape is {random_image_tensor.shape} => \n{random_image_tensor }")

Dimention = 3 and shape is torch.Size([3, 224, 224]) => 
tensor([[[0.2886, 0.4096, 0.9800,  ..., 0.1346, 0.9834, 0.9771],
         [0.5738, 0.7864, 0.9264,  ..., 0.8288, 0.3606, 0.9132],
         [0.0023, 0.8566, 0.0793,  ..., 0.7444, 0.8621, 0.1904],
         ...,
         [0.0592, 0.3673, 0.9390,  ..., 0.1867, 0.4278, 0.8327],
         [0.4996, 0.6619, 0.8476,  ..., 0.5817, 0.3917, 0.1646],
         [0.5487, 0.4351, 0.2470,  ..., 0.3910, 0.1069, 0.8579]],

        [[0.2396, 0.4505, 0.6808,  ..., 0.4228, 0.8626, 0.3239],
         [0.8871, 0.7540, 0.5141,  ..., 0.8839, 0.5882, 0.5478],
         [0.2657, 0.8431, 0.4402,  ..., 0.4380, 0.6298, 0.6347],
         ...,
         [0.7300, 0.2860, 0.2857,  ..., 0.3702, 0.2321, 0.5851],
         [0.8880, 0.3386, 0.7286,  ..., 0.0186, 0.6056, 0.9278],
         [0.1901, 0.9913, 0.5973,  ..., 0.9937, 0.0404, 0.7777]],

        [[0.2347, 0.1588, 0.2284,  ..., 0.2526, 0.9394, 0.1930],
         [0.5068, 0.7643, 0.0052,  ..., 0.4692, 0.6137, 0.0163],
 

In [34]:
# HandWriting at 16 * 16 black and white
# black < 0.5 / white >= 0
rand_handwriting_00 = torch.rand(2,16,16)
rand_handwriting_00

tensor([[[0.6375, 0.8320, 0.6640, 0.6800, 0.3913, 0.1602, 0.4422, 0.3464,
          0.6546, 0.3866, 0.1079, 0.9233, 0.4466, 0.7706, 0.6317, 0.8033],
         [0.6270, 0.1359, 0.0730, 0.7324, 0.9979, 0.6823, 0.3900, 0.5637,
          0.3238, 0.9241, 0.2874, 0.2298, 0.2089, 0.4040, 0.1484, 0.0902],
         [0.2481, 0.2871, 0.8220, 0.1816, 0.9463, 0.2705, 0.6122, 0.6345,
          0.1048, 0.2520, 0.8032, 0.2739, 0.8544, 0.2983, 0.5343, 0.4903],
         [0.2227, 0.1956, 0.5550, 0.8240, 0.3196, 0.4591, 0.1900, 0.1689,
          0.4122, 0.6289, 0.5997, 0.2447, 0.6253, 0.9154, 0.8999, 0.1997],
         [0.9272, 0.9745, 0.8811, 0.9338, 0.8537, 0.2429, 0.2328, 0.3609,
          0.1684, 0.7031, 0.4384, 0.9998, 0.0062, 0.6465, 0.7526, 0.5851],
         [0.7676, 0.8486, 0.7520, 0.5405, 0.0864, 0.5892, 0.6682, 0.8429,
          0.1072, 0.8080, 0.7893, 0.5096, 0.4610, 0.5466, 0.1659, 0.0078],
         [0.6292, 0.7611, 0.8238, 0.8944, 0.2684, 0.4201, 0.0456, 0.7245,
          0.9838, 0.9171, 0.7990

## Zeros and ones

Sometimes you'll just want to fill tensors with zeros or ones.

This happens a lot with masking (like masking some of the values in one tensor with zeros to let a model know not to learn them).

In [35]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,3))
print(f"Structure -> \n{zeros}\nType : {zeros.dtype}")

Structure -> 
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
Type : torch.float32


In [36]:
# Create a tensor of all one
ones = torch.ones(size=(3,4))
print(f"Structure -> \n{ones}\nType : {ones.dtype}")

Structure -> 
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
Type : torch.float32


##Creating a range and tensors like
Sometimes you might want a range of numbers, such as 1 to 10 or 0 to 100.

You can use torch.arange(start, end, step) to do so.

Where:

* start = start of range (e.g. 0)
* end = end of range (e.g. 10)
* step = how many steps in between each value (e.g. 1)

In [37]:
# 1 until 20 just odd
Xodd = torch.arange(1,20,2)
Xodd

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [38]:
# 1 until 20 just even
Xeven = torch.arange(2,21,2)
Xeven

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [39]:
XFive = torch.arange(0,51,5)
XFive

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])


Sometimes you might want one tensor of a certain type with the same shape as another tensor.

For example, a tensor of all zeros with the same shape as a previous tensor.

To do so you can use torch.zeros_like(input) or torch.ones_like(input) which return a tensor filled with zeros or ones in the same shape as the input respectively.

In [40]:
XFive.shape

torch.Size([11])

In [41]:
X_Shape_Copy1 = torch.zeros_like(input=XFive)
X_Shape_Copy1, X_Shape_Copy1.shape, X_Shape_Copy1.dtype

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), torch.Size([11]), torch.int64)

In [42]:
X_Shape_Copy2 = torch.ones_like(X_Shape_Copy1)
X_Shape_Copy2, X_Shape_Copy2.shape, X_Shape_Copy2.dtype

(tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]), torch.Size([11]), torch.int64)


##Tensor datatypes
There are many different tensor datatypes available in PyTorch.
link: https://docs.pytorch.org/docs/stable/tensors.html#data-types

Some are specific for CPU and some are better for GPU.

Getting to know which one can take some time.

Generally if you see torch.cuda anywhere, the tensor is being used for GPU (since Nvidia GPUs use a computing toolkit called CUDA).

The most common type (and generally the default) is torch.float32 or torch.float.

This is referred to as "32-bit floating point".

But there's also 16-bit floating point (torch.float16 or torch.half) and 64-bit floating point (torch.float64 or torch.double).

And to confuse things even more there's also 8-bit, 16-bit, 32-bit and 64-bit integers.

Plus more!

Note: An integer is a flat round number like 7 whereas a float has a decimal 7.0.

The reason for all of these is to do with precision in computing.

Precision is the amount of detail used to describe a number.

The higher the precision value (8, 16, 32), the more detail and hence data used to express a number.

This matters in deep learning and numerical computing because you're making so many operations, the more detail you have to calculate on, the more compute you have to use.

So lower precision datatypes are generally faster to compute on but sacrifice some performance on evaluation metrics like accuracy (faster to compute but less accurate).

Resources:
https://docs.pytorch.org/docs/stable/tensors.html#data-types

https://en.wikipedia.org/wiki/Precision_(computer_science)

See the PyTorch documentation for a list of all available tensor datatypes.
Read the Wikipedia page for an overview of what precision in computing) is.
Let's see how to create some tensors with specific datatypes. We can do so using the dtype paramete

In [43]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))


Aside from shape issues (tensor shapes don't match up), two of the other most common issues you'll come across in PyTorch are datatype and device issues.

For example, one of tensors is torch.float32 and the other is torch.float16 (PyTorch often likes tensors to be the same format).

Or one of your tensors is on the CPU and the other is on the GPU (PyTorch likes calculations between tensors to be on the same device).

We'll see more of this device talk later on.

For now let's create a tensor with dtype=torch.float16.

In [45]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16