<a href="https://colab.research.google.com/github/ErfanEbFiN79/Erfan-Python/blob/main/Python%20Erfan/PyTorch/Learn_01/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [409]:
!nvidia-smi

Thu Oct 30 16:02:33 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   50C    P0             26W /   70W |     104MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [410]:
import torch

In [411]:
print(torch.__version__)

2.8.0+cu126


## Introduction to Tensors
Creating Tensors

Scalers are linear (or more precisely affine) transformers and differ from each other in the way they estimate the parameters used to shift and scale each feature. QuantileTransformer provides non-linear transformations in which distances between marginal outliers and inliers are shrunk.

PyTorch tensors are created usin torch.Tensor()

In [412]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [413]:
scalar.ndim

0

In [414]:
# Get tensor back as python int
scalar.item()

7

In [415]:
scalar2 = torch.tensor(3)
print(f"Scalar:{scalar2}\nDimention:{scalar2.ndim}\nItem:{scalar2.item()}\nShape:{scalar2.shape}")

Scalar:3
Dimention:0
Item:3
Shape:torch.Size([])


In [416]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [417]:
vector.ndim

1

In [418]:
vector.shape

torch.Size([2])

In [419]:
vector2 = torch.tensor([0,8])
print(f"Vector:{vector2}\nDimention:{vector2.ndim}\nShape:{vector2.shape},{vector2.size()}")

Vector:tensor([0, 8])
Dimention:1
Shape:torch.Size([2]),torch.Size([2])


In [420]:
# Matrix
Matrix = torch.tensor([[7,8],[9,10]])
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [421]:
Matrix.ndim

2

In [422]:
Matrix.size()

torch.Size([2, 2])

In [423]:
Matrix.shape

torch.Size([2, 2])

In [424]:
type(Matrix)

torch.Tensor

In [425]:
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [426]:
Matrix[0]

tensor([7, 8])

In [427]:
Matrix[1]

tensor([ 9, 10])

In [428]:
# Another matrix

matrix2 = torch.tensor([[0,1,0],[1,0,1]])
print(f"Matrix:{matrix2}\nDimention:{matrix2.ndim}\nShape:{matrix2.shape}\nType:{type(matrix2)}")

Matrix:tensor([[0, 1, 0],
        [1, 0, 1]])
Dimention:2
Shape:torch.Size([2, 3])
Type:<class 'torch.Tensor'>


In [429]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [430]:
TENSOR.ndim

3

In [431]:
TENSOR.shape

torch.Size([1, 3, 3])

In [432]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [433]:
TENSOR[0][0]

tensor([1, 2, 3])

In [434]:
TENSOR[0][2]

tensor([2, 4, 5])

In [435]:
TENSOR[0][1][1]

tensor(6)

In [436]:
MyTensorTest = torch.tensor([[[1,2,3],
                              [4,5,6],
                              [7,8,9]],
                             [[10,12,13],
                              [14,16,17],
                              [18,19,20]]])

In [437]:
MyTensorTest.shape

torch.Size([2, 3, 3])

In [438]:
MyTensorTest.ndim

3

In [439]:
MyTensorTest[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [440]:
MyTensorTest[1]

tensor([[10, 12, 13],
        [14, 16, 17],
        [18, 19, 20]])

In [441]:
# if we want to get a 16 from the Tesnor
MyTensorTest[1][1][1]

tensor(16)

### Random Tensor

We've established tensors represent some form of data.

And machine learning models such as neural networks manipulate and seek patterns within tensors.

But when building machine learning models with PyTorch, it's rare you'll create tensors by hand (like what we've been doing).

Instead, a machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

In essence:

'Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...'

As a data scientist, you can define how the machine learning model starts (initialization), looks at data (representation) and updates (optimization) its random numbers.

rand duc => https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [442]:
rand_tensor_1 = torch.rand(3)
rand_tensor_2 = torch.rand(3,4)
rand_tensor_3 = torch.rand(2,3,8)
print(f"{rand_tensor_1} has {rand_tensor_1.ndim} dimentions and the shape is {rand_tensor_1.shape} and type is {rand_tensor_1.dtype}\n")
print(f"{rand_tensor_2} has {rand_tensor_2.ndim} dimentions and the shape is {rand_tensor_2.shape} and type is {rand_tensor_2.dtype}\n")
print(f"{rand_tensor_3} has {rand_tensor_3.ndim} dimentions and the shape is {rand_tensor_3.shape} and type is {rand_tensor_3.dtype}\n")

tensor([0.8694, 0.5677, 0.7411]) has 1 dimentions and the shape is torch.Size([3]) and type is torch.float32

tensor([[0.4294, 0.8854, 0.5739, 0.2666],
        [0.6274, 0.2696, 0.4414, 0.2969],
        [0.8317, 0.1053, 0.2695, 0.3588]]) has 2 dimentions and the shape is torch.Size([3, 4]) and type is torch.float32

tensor([[[0.1994, 0.5472, 0.0062, 0.9516, 0.0753, 0.8860, 0.5832, 0.3376],
         [0.8090, 0.5779, 0.9040, 0.5547, 0.3423, 0.6343, 0.3644, 0.7104],
         [0.9464, 0.7890, 0.2814, 0.7886, 0.5895, 0.7539, 0.1952, 0.0050]],

        [[0.3068, 0.1165, 0.9103, 0.6440, 0.7071, 0.6581, 0.4913, 0.8913],
         [0.1447, 0.5315, 0.1587, 0.6542, 0.3278, 0.6532, 0.3958, 0.9147],
         [0.2036, 0.2018, 0.2018, 0.9497, 0.6666, 0.9811, 0.0874, 0.0041]]]) has 3 dimentions and the shape is torch.Size([2, 3, 8]) and type is torch.float32



The flexibility of torch.rand() is that we can adjust the size to be whatever we want.

For example, say you wanted a random tensor in the common image shape of [224, 224, 3] ([height, width, color_channels]).

In [443]:
random_image_tensor = torch.rand(size=(3,224,224))
print(f"Dimention = {random_image_tensor.ndim} and shape is {random_image_tensor.shape} => \n{random_image_tensor }")

Dimention = 3 and shape is torch.Size([3, 224, 224]) => 
tensor([[[0.1088, 0.1637, 0.7025,  ..., 0.1786, 0.4610, 0.3335],
         [0.3382, 0.5161, 0.3939,  ..., 0.4419, 0.8127, 0.4538],
         [0.8136, 0.8615, 0.0659,  ..., 0.1774, 0.2730, 0.8497],
         ...,
         [0.6445, 0.3753, 0.5286,  ..., 0.3480, 0.0642, 0.8361],
         [0.6437, 0.9456, 0.4008,  ..., 0.7583, 0.9380, 0.1962],
         [0.1488, 0.8536, 0.3953,  ..., 0.7424, 0.6487, 0.3460]],

        [[0.0066, 0.7406, 0.7848,  ..., 0.6263, 0.7894, 0.7856],
         [0.1229, 0.9387, 0.0767,  ..., 0.6635, 0.1255, 0.1472],
         [0.6185, 0.8058, 0.0387,  ..., 0.7351, 0.8390, 0.6640],
         ...,
         [0.9189, 0.5698, 0.1084,  ..., 0.3217, 0.1258, 0.7432],
         [0.1262, 0.4578, 0.8054,  ..., 0.5604, 0.7359, 0.6811],
         [0.0823, 0.5328, 0.0823,  ..., 0.9397, 0.1061, 0.4857]],

        [[0.5883, 0.4657, 0.5152,  ..., 0.2691, 0.1899, 0.6119],
         [0.3753, 0.2337, 0.0763,  ..., 0.3777, 0.2914, 0.8917],
 

In [444]:
# HandWriting at 16 * 16 black and white
# black < 0.5 / white >= 0
rand_handwriting_00 = torch.rand(2,16,16)
rand_handwriting_00

tensor([[[4.0085e-01, 2.8919e-01, 9.9772e-01, 6.6492e-01, 5.6462e-01,
          9.3226e-01, 4.6214e-01, 4.0274e-01, 1.6801e-01, 1.1699e-01,
          5.0632e-01, 6.0612e-01, 5.1413e-01, 1.9070e-01, 4.4532e-02,
          5.4252e-01],
         [9.5797e-01, 9.9667e-01, 6.4170e-01, 8.3910e-02, 7.6465e-02,
          5.9118e-01, 8.8924e-01, 4.2512e-01, 8.7012e-01, 1.4724e-01,
          6.9807e-01, 4.9645e-01, 3.8084e-02, 8.4727e-01, 4.4492e-01,
          7.7012e-02],
         [4.6260e-01, 7.8997e-01, 2.4831e-01, 8.1601e-01, 1.1684e-01,
          9.1583e-01, 9.1073e-01, 8.8967e-01, 5.1552e-01, 5.0669e-01,
          7.7875e-01, 9.5699e-01, 2.6579e-01, 6.6929e-01, 7.9036e-01,
          1.4294e-01],
         [2.5960e-01, 3.5066e-01, 6.6825e-01, 4.6015e-01, 9.5449e-01,
          1.9359e-01, 8.1985e-01, 3.7517e-01, 6.2613e-01, 6.4558e-01,
          1.4002e-01, 8.2157e-01, 6.6705e-01, 1.1672e-01, 3.5705e-01,
          5.3859e-01],
         [2.6620e-01, 1.3533e-01, 1.6636e-01, 5.6199e-01, 3.3370e-01

## Zeros and ones

Sometimes you'll just want to fill tensors with zeros or ones.

This happens a lot with masking (like masking some of the values in one tensor with zeros to let a model know not to learn them).

In [445]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,3))
print(f"Structure -> \n{zeros}\nType : {zeros.dtype}")

Structure -> 
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
Type : torch.float32


In [446]:
# Create a tensor of all one
ones = torch.ones(size=(3,4))
print(f"Structure -> \n{ones}\nType : {ones.dtype}")

Structure -> 
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
Type : torch.float32


##Creating a range and tensors like
Sometimes you might want a range of numbers, such as 1 to 10 or 0 to 100.

You can use torch.arange(start, end, step) to do so.

Where:

* start = start of range (e.g. 0)
* end = end of range (e.g. 10)
* step = how many steps in between each value (e.g. 1)

In [447]:
# 1 until 20 just odd
Xodd = torch.arange(1,20,2)
Xodd

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [448]:
# 1 until 20 just even
Xeven = torch.arange(2,21,2)
Xeven

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [449]:
XFive = torch.arange(0,51,5)
XFive

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])


Sometimes you might want one tensor of a certain type with the same shape as another tensor.

For example, a tensor of all zeros with the same shape as a previous tensor.

To do so you can use torch.zeros_like(input) or torch.ones_like(input) which return a tensor filled with zeros or ones in the same shape as the input respectively.

In [450]:
XFive.shape

torch.Size([11])

In [451]:
X_Shape_Copy1 = torch.zeros_like(input=XFive)
X_Shape_Copy1, X_Shape_Copy1.shape, X_Shape_Copy1.dtype

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), torch.Size([11]), torch.int64)

In [452]:
X_Shape_Copy2 = torch.ones_like(X_Shape_Copy1)
X_Shape_Copy2, X_Shape_Copy2.shape, X_Shape_Copy2.dtype

(tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]), torch.Size([11]), torch.int64)


##Tensor datatypes
There are many different tensor datatypes available in PyTorch.
link: https://docs.pytorch.org/docs/stable/tensors.html#data-types

Some are specific for CPU and some are better for GPU.

Getting to know which one can take some time.

Generally if you see torch.cuda anywhere, the tensor is being used for GPU (since Nvidia GPUs use a computing toolkit called CUDA).

The most common type (and generally the default) is torch.float32 or torch.float.

This is referred to as "32-bit floating point".

But there's also 16-bit floating point (torch.float16 or torch.half) and 64-bit floating point (torch.float64 or torch.double).

And to confuse things even more there's also 8-bit, 16-bit, 32-bit and 64-bit integers.

Plus more!

Note: An integer is a flat round number like 7 whereas a float has a decimal 7.0.

The reason for all of these is to do with precision in computing.

Precision is the amount of detail used to describe a number.

The higher the precision value (8, 16, 32), the more detail and hence data used to express a number.

This matters in deep learning and numerical computing because you're making so many operations, the more detail you have to calculate on, the more compute you have to use.

So lower precision datatypes are generally faster to compute on but sacrifice some performance on evaluation metrics like accuracy (faster to compute but less accurate).

Resources:
https://docs.pytorch.org/docs/stable/tensors.html#data-types

https://en.wikipedia.org/wiki/Precision_(computer_science)

See the PyTorch documentation for a list of all available tensor datatypes.
Read the Wikipedia page for an overview of what precision in computing) is.
Let's see how to create some tensors with specific datatypes. We can do so using the dtype paramete

In [453]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))


Aside from shape issues (tensor shapes don't match up), two of the other most common issues you'll come across in PyTorch are datatype and device issues.

For example, one of tensors is torch.float32 and the other is torch.float16 (PyTorch often likes tensors to be the same format).

Or one of your tensors is on the CPU and the other is on the GPU (PyTorch likes calculations between tensors to be on the same device).

We'll see more of this device talk later on.

For now let's create a tensor with dtype=torch.float16.

In [454]:
float_32_tensor.dtype

torch.float32

In [455]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [456]:
float_16_tensor2 = float_32_tensor.type(torch.float16)
float_16_tensor2

tensor([3., 6., 9.], dtype=torch.float16)

In [457]:
# WOW, We can do this
float_32_tensor * float_16_tensor
# but try to use same data type, ok??
# because: maby get error at large database

tensor([ 9., 36., 81.])

In [458]:
float_16_mulb_32 = float_32_tensor * float_16_tensor
float_16_mulb_32.dtype

torch.float32

In [459]:
int_32_tensor = torch.tensor([1,2,3], dtype=torch.int32)
int_32_tensor

tensor([1, 2, 3], dtype=torch.int32)

In [460]:
(float_32_tensor * int_32_tensor).dtype
# Wow it's work too :/

torch.float32

### Getting information from tensors
Once you've created tensors (or someone else or a PyTorch module has created them for you), you might want to get some information from them.

We've seen these before but three of the most common attributes you'll want to find out about tensors are:

1. shape - what shape is the tensor? (some operations require specific shape rules)
2. dtype - what datatype are the elements within the tensor stored in?
3. device - what device is the tensor stored on? (usually GPU or CPU)

Let's create a random tensor and find out details about it.

In [461]:
# Create a tensor
exTensor1 = torch.arange(0,11,2)
exTensor1

tensor([ 0,  2,  4,  6,  8, 10])

In [462]:
# Find out details about <exTensor1>
print(exTensor1)
print(f"Datatype of tensor: {exTensor1.dtype}")
print(f"Shape of tensor: {exTensor1.shape}")
print(f"Dimenstion of tensor: {exTensor1.ndim}")
print(f"Device tensor is on: {exTensor1.device}")

tensor([ 0,  2,  4,  6,  8, 10])
Datatype of tensor: torch.int64
Shape of tensor: torch.Size([6])
Dimenstion of tensor: 1
Device tensor is on: cpu


In [463]:
print(XFive)
print(f"Shape : {XFive.shape}")
print(f"Data type : {XFive.dtype}")
print(f"Dimenstion : {XFive.ndim}")
print(f"Device : {XFive.device}")

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])
Shape : torch.Size([11])
Data type : torch.int64
Dimenstion : 1
Device : cpu


## Manipulating tensors (tensor operations)

Manipulating tensors (tensor operations)¶
In deep learning, data (images, text, video, audio, protein structures, etc) gets represented as tensors.

A model learns by investigating those tensors and performing a series of operations (could be 1,000,000s+) on tensors to create a representation of the patterns in the input data.

These operations are often a wonderful dance between:

* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication
And that's it. Sure there are a few more here and there but these are the basic building blocks of neural networks.

Stacking these building blocks in the right way, you can create the most sophisticated of neural networks (just like lego!).

In [464]:
exTensor1

tensor([ 0,  2,  4,  6,  8, 10])

In [465]:
# Let's + 10 to the each of the elements
exTensor1 + 10

tensor([10, 12, 14, 16, 18, 20])

In [466]:
# Lets try *
%%time
exTensor1 * 10

CPU times: user 46 µs, sys: 4 µs, total: 50 µs
Wall time: 52.9 µs


tensor([  0,  20,  40,  60,  80, 100])

In [467]:
%%time
torch.multiply(exTensor1, 10)

CPU times: user 50 µs, sys: 0 ns, total: 50 µs
Wall time: 53.2 µs


tensor([  0,  20,  40,  60,  80, 100])

In [468]:
# When you dont use = that means you don't change
#    the origin value, just you see a results
exTensor1

tensor([ 0,  2,  4,  6,  8, 10])

PyTorch also has a bunch of built-in functions like torch.mul() (short for multiplication) and torch.add() to perform basic operations.

In [469]:
# Insted of * we can us multiply funation
torch.multiply(exTensor1, 10)

tensor([  0,  20,  40,  60,  80, 100])

In [470]:
# Insted of + we can us add function
print(torch.add(exTensor1, 10))
print(torch.add(exTensor1, exTensor1))

tensor([10, 12, 14, 16, 18, 20])
tensor([ 0,  4,  8, 12, 16, 20])


! However, it's more common to use the operator symbols like * instead of torch.mul()


## Matrix multiplication (is all you need)
One of the most common operations in machine learning and deep learning algorithms (like neural networks) is matrix multiplication.


PyTorch implements matrix multiplication functionality in the torch.matmul() method.

The main two rules for matrix multiplication to remember are:

1. The **inner dimensions** must match:
* (3, 2) @ (3, 2) won't work
* (2, 3) @ (3, 2) will work
* (3, 2) @ (2, 3) will work
The resulting matrix has the shape of
2. the **outer dimensions**:
* '(2, 3) @ (3, 2)' -> '(2, 2)'
* '(3, 2) @ (2, 3)' -> '(3, 3)'

Note: "@" in Python is the symbol for matrix multiplication.

Resource: You can see all of the rules for matrix multiplication using torch.matmul() in the PyTorch documentation.

In [471]:
exTensor1

tensor([ 0,  2,  4,  6,  8, 10])

In [472]:
torch.matmul(exTensor1, exTensor1)

tensor(220)

In [473]:
exTensor1 @ exTensor1

tensor(220)


You can do matrix multiplication by hand but it's not recommended.

The in-built torch.matmul() method is faster.

In [474]:
exTensor2_1 = torch.tensor([[1,2],
                           [3,4],
                           [5,6]])

exTensor2_2 = torch.tensor([[7,10],
                             [8,11],
                             [9,12]])


## One of the most common errors in deep learning (shape errors)
Because much of deep learning is multiplying and performing operations on matrices and matrices have a strict rule about what shapes and sizes can be combined, one of the most common errors you'll run into in deep learning is shape mismatches.

In [475]:
exTensor2_1.shape

torch.Size([3, 2])

In [476]:
exTensor2_2.shape

torch.Size([3, 2])

we can do matrix multiplication becase it's broke role one
for exTensor2_1 and exTensor2_2
**we need transpose one of them**

One of the ways to do this is with a transpose (switch the dimensions of a given tensor).

You can perform transposes in PyTorch using either:

* torch.transpose(input, dim0, dim1) - where input is the desired tensor to transpose and dim0 and dim1 are the dimensions to be swapped.
* tensor.T - where tensor is the desired tensor to transpose.

In [477]:
print(exTensor2_1)
print("\n")
print(exTensor2_2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])


In [478]:
print(exTensor2_1)
print("\n")
print(exTensor2_2.T)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


tensor([[ 7,  8,  9],
        [10, 11, 12]])


In [479]:
exTensor2_2_New = exTensor2_2.T

In [480]:
# The operation works when tensor_B is transposed
print(f"Original shapes: exTensor2_1 = {exTensor2_1.shape}, exTensor2_2= {exTensor2_2.shape}\n")
print(f"New shapes: exTensor2_1 = {exTensor2_1.shape} (same as above), exTensor2_2 = {exTensor2_2.T.shape}\n")
print(f"Multiplying: {exTensor2_1.shape} * {exTensor2_2.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(exTensor2_1, exTensor2_2.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: exTensor2_1 = torch.Size([3, 2]), exTensor2_2= torch.Size([3, 2])

New shapes: exTensor2_1 = torch.Size([3, 2]) (same as above), exTensor2_2 = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


Without the transpose, the rules of matrix multiplication aren't fulfilled and we get an error like above.

How about a visual?

![visual demo of matrix multiplication](https://github.com/mrdbourke/pytorch-deep-learning/raw/main/images/00-matrix-multiply-crop.gif)

You can create your own matrix multiplication visuals like this at http://matrixmultiplication.xyz/.

> **Note:** A matrix multiplication like this is also referred to as the [**dot product**](https://www.mathsisfun.com/algebra/vectors-dot-product.html) of two matrices.



Neural networks are full of matrix multiplications and dot products.

The [`torch.nn.Linear()`](https://pytorch.org/docs/1.9.1/generated/torch.nn.Linear.html) module (we'll see this in action later on), also known as a feed-forward layer or fully connected layer, implements a matrix multiplication between an input `x` and a weights matrix `A`.

$$
y = x\cdot{A^T} + b
$$

Where:
* `x` is the input to the layer (deep learning is a stack of layers like `torch.nn.Linear()` and others on top of each other).
* `A` is the weights matrix created by the layer, this starts out as random numbers that get adjusted as a neural network learns to better represent patterns in the data (notice the "`T`", that's because the weights matrix gets transposed).
  * **Note:** You might also often see `W` or another letter like `X` used to showcase the weights matrix.
* `b` is the bias term used to slightly offset the weights and inputs.
* `y` is the output (a manipulation of the input in the hopes to discover patterns in it).

This is a linear function (you may have seen something like $y = mx+b$ in high school or elsewhere), and can be used to draw a straight line!

Let's play around with a linear layer.

Try changing the values of `in_features` and `out_features` below and see what happens.

Do you notice anything to do with the shapes?

In [481]:
exTensor2_1, exTensor2_1.shape

(tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 torch.Size([3, 2]))

In [482]:
exTensor2_2_New, exTensor2_2_New.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [483]:
exTensorR1 = exTensor2_1 @ exTensor2_2_New

In [484]:
print(exTensorR1)
print(f"Shape : {exTensorR1.shape}")
print(f"Dimenstion : {exTensorR1.ndim}")
print(f"Datatype : {exTensorR1.dtype}")
print(f"Device : {exTensorR1.device}")

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
Shape : torch.Size([3, 3])
Dimenstion : 2
Datatype : torch.int64
Device : cpu



## Finding the min, max, mean, sum, etc (aggregation)
Now we've seen a few ways to manipulate tensors, let's run through a few ways to aggregate them (go from more values to less values).

In [485]:
exTensorR1

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [486]:
#Find Min
exTensorR1.min()

tensor(27)

In [487]:
#Find Max
exTensorR1.max()

tensor(117)

In [488]:
#Find mean
exTensorR1.type(torch.float32).mean()

tensor(68.)

> **Note:** You may find some methods such as `torch.mean()` require tensors to be in `torch.float32` (the most common) or another specific datatype, otherwise the operation will fail.



In [489]:
# Sum of elements
exTensorR1.sum()

tensor(612)

You can also do the same as above with `torch` methods.

In [490]:
torch.min(exTensorR1), torch.max(exTensorR1)

(tensor(27), tensor(117))

In [491]:
torch.mean(exTensorR1.type(torch.float32)), torch.sum(exTensorR1)

(tensor(68.), tensor(612))

## Finding position of min and max value

This is helpful incase you just want the position where the highest (or lowest) value is and not the actual value itself (we'll see this in a later section when using the [softmax activation function](https://pytorch.org/docs/stable/generated/torch.nn.Softmax.html)).

In [492]:
import random

In [493]:
def BackRandom():
  return random.randint(1, 50)

In [494]:
exTensor2 = torch.tensor([BackRandom(),BackRandom(),BackRandom()])

In [495]:
exTensor2.argmax()

tensor(0)

In [496]:
exTensor2.argmin()

tensor(2)

In [497]:
exTensor2[2]

tensor(1)

In [498]:
exTensor2[1]

tensor(49)

In [499]:
exTensor2

tensor([49, 49,  1])

In [500]:
exTensor3 = torch.arange(BackRandom(), BackRandom())

In [501]:
exTensor3.argmax()

tensor(3)

In [502]:
exTensor3.argmin()

tensor(0)

In [503]:
exTensor3

tensor([38, 39, 40, 41])

### Reshaping, stacking, squeezing and unsqueezing

Often times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them.

To do so, some popular methods are:

| Method | One-line description |
| ----- | ----- |
| [`torch.reshape(input, shape)`](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape) | Reshapes `input` to `shape` (if compatible), can also use `torch.Tensor.reshape()`. |
| [`Tensor.view(shape)`](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html) | Returns a view of the original tensor in a different `shape` but shares the same data as the original tensor. |
| [`torch.stack(tensors, dim=0)`](https://pytorch.org/docs/1.9.1/generated/torch.stack.html) | Concatenates a sequence of `tensors` along a new dimension (`dim`), all `tensors` must be same size. |
| [`torch.squeeze(input)`](https://pytorch.org/docs/stable/generated/torch.squeeze.html) | Squeezes `input` to remove all the dimenions with value `1`. |
| [`torch.unsqueeze(input, dim)`](https://pytorch.org/docs/1.9.1/generated/torch.unsqueeze.html) | Returns `input` with a dimension value of `1` added at `dim`. |
| [`torch.permute(input, dims)`](https://pytorch.org/docs/stable/generated/torch.permute.html) | Returns a *view* of the original `input` with its dimensions permuted (rearranged) to `dims`. |

Why do any of these?

Because deep learning models (neural networks) are all about manipulating tensors in some way. And because of the rules of matrix multiplication, if you've got shape mismatches, you'll run into errors. These methods help you make sure the right elements of your tensors are mixing with the right elements of other tensors.

Let's try them out.

In [504]:
exTensor4 = torch.arange(1., 10.)

In [505]:
exTensor4, exTensor4.shape, exTensor4.ndim

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), 1)

Now let's add an extra dimension with `torch.reshape()`.

In [506]:
# Add tree extra dimension
exTensor4.reshape(3,3), exTensor4.shape, exTensor4.ndim

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([9]),
 1)

In [507]:
# Add an extra dimension
exTensor4.reshape(1,9), exTensor4.shape, exTensor4.ndim

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([9]), 1)

We can also change the view with `torch.view()`.

In [508]:
exTensor4

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [509]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
exTensorR2 = exTensor4.view(3,3)
print(f"exTensorR2 shape: {exTensorR2.shape} / exTensor4 shape: {exTensor4.shape}")


exTensorR2 shape: torch.Size([3, 3]) / exTensor4 shape: torch.Size([9])


Remember though, changing the view of a tensor with `torch.view()` really only creates a new view of the *same* tensor.

So changing the view changes the original tensor too.

In [510]:
# changing exTensorR2 alose change exTensor4
exTensorR2[:, 0] = 5
exTensorR2, exTensor4

(tensor([[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]),
 tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]))

If we wanted to stack our new tensor on top of itself five times, we could do so with `torch.stack()`.

> NOTE: After this note `x` means **tensor**

In [511]:
x_stacked1 = torch.stack([exTensor4,exTensor4], dim=0)
x_stacked1

tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.]])

In [512]:
x_stacked1 = torch.stack([exTensor4,exTensor4], dim=1)
x_stacked1

tensor([[5., 5.],
        [2., 2.],
        [3., 3.],
        [5., 5.],
        [5., 5.],
        [6., 6.],
        [5., 5.],
        [8., 8.],
        [9., 9.]])

How about removing all single dimensions from a tensor?

To do so you can use `torch.squeeze()` (I remember this as *squeezing* the tensor to only have dimensions over 1).

In [513]:
#Create a tensor
exX4 = torch.arange(1., 8.)
exX4 = exX4.reshape(1,7)
print(f"Previous tensor: {exX4}")
print(f"Previous shape: {exX4.shape}")

# Remove extra dimension from x_reshaped
exX4 = exX4.squeeze()
print(f"\nNew tensor: {exX4}")
print(f"New shape: {exX4.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [514]:
# Tensor with multiple dimensions of size 1
x = torch.randn(3, 1, 4, 1, 5)
print(f"Original tensor shape: {x.shape}")

# Squeeze all dimensions of size 1
y = torch.squeeze(x)
print(f"Squeezed tensor shape (all): {y.shape}")

# Squeeze a specific dimension (if its size is 1)
z = torch.squeeze(x, dim=1) # Squeezes the second dimension (index 1)
print(f"Squeezed tensor shape (dim=1): {z.shape}")

w = torch.squeeze(x, dim=0) # Does not squeeze, as dim 0 has size 3
print(f"Squeezed tensor shape (dim=0): {w.shape}")

Original tensor shape: torch.Size([3, 1, 4, 1, 5])
Squeezed tensor shape (all): torch.Size([3, 4, 5])
Squeezed tensor shape (dim=1): torch.Size([3, 4, 1, 5])
Squeezed tensor shape (dim=0): torch.Size([3, 1, 4, 1, 5])


And to do the reverse of `torch.squeeze()` you can use `torch.unsqueeze()` to add a dimension value of 1 at a specific index.

In [515]:
print(f"\nNew tensor: {exX4}")
print(f"New shape: {exX4.shape}")
## Add an extra dimension with unsqueeze

exX4 = exX4.unsqueeze(dim=0)
print(f"\nNew tensor: {exX4}")
print(f"New shape: {exX4.shape}")


New tensor: tensor([1., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


You can also rearrange the order of axes values with `torch.permute(input, dims)`, where the `input` gets turned into a *view* with new `dims`.

In [516]:
# Create tensor with specific shape
x_image1 = torch.rand(size=(224,224,3)) #size => 0, size => 1, rgb => 2


x_image_permuted = x_image1.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_image1.shape}")
print(f"New shape: {x_image_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [517]:
# Think we save a data for a system like that
# system code:
# code => 0
# code_Key => 1
# key => 2
# key_load => 3
x_Code = torch.rand(size = (10,9,5,6))
print(f"x_Home1_Shape: {x_Code.shape}")
x_Code1_permuted = x_Code.permute(3,2,1,0)
print(f"x_Code1_permuted: {x_Code1_permuted.shape}")

x_Home1_Shape: torch.Size([10, 9, 5, 6])
x_Code1_permuted: torch.Size([6, 5, 9, 10])


## Indexing (selecting data from tensors)

Sometimes you'll want to select specific data from tensors (for example, only the first column or second row).

To do so, you can use indexing.

If you've ever done indexing on Python lists or NumPy arrays, indexing in PyTorch with tensors is very similar.

In [518]:
# Create new tensor
exX5 = torch.arange(1,10).reshape(1,3,3)
print(f"Tensor:\n {exX5}\nShape: \n{exX5.shape}")

Tensor:
 tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Shape: 
torch.Size([1, 3, 3])


In [519]:
# Let's just quick look at our tensor
exX5

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [520]:
exX5[0] # => We have 3 layers now we get layer 1

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [521]:
print(f"Datas on the first row {exX5[0][0]}")
print(f"Datas on the Secend row {exX5[0][1]}")
print(f"Datas on the Theerd row {exX5[0][2]}")

Datas on the first row tensor([1, 2, 3])
Datas on the Secend row tensor([4, 5, 6])
Datas on the Theerd row tensor([7, 8, 9])


In [522]:
print(f"Data on the middle: {exX5[0][1][1]}")

Data on the middle: 5


You can also use `:` to specify "all values in this dimension" and then use a comma (`,`) to add another dimension.

In [523]:
exX5[:,:,:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [524]:
print(f"Datas on the first column {exX5[:,:,0]}")
print(f"Datas on the Secend column {exX5[:,:,1]}")
print(f"Datas on the Theerd column {exX5[:,:,2]}")

Datas on the first column tensor([[1, 4, 7]])
Datas on the Secend column tensor([[2, 5, 8]])
Datas on the Theerd column tensor([[3, 6, 9]])


In [525]:
print(f"Datas of middle row: {exX5[:,1,:]}")

Datas of middle row: tensor([[4, 5, 6]])


Indexing can be quite confusing to begin with, especially with larger tensors (I still have to try indexing multiple times to get it right). But with a bit of practice and following the data explorer's motto (***visualize, visualize, visualize***), you'll start to get the hang of it.

## PyTorch tensors & NumPy

Since NumPy is a popular Python numerical computing library, PyTorch has functionality to interact with it nicely.  

The two main methods you'll want to use for NumPy to PyTorch (and back again) are:
* [`torch.from_numpy(ndarray)`](https://pytorch.org/docs/stable/generated/torch.from_numpy.html) - NumPy array -> PyTorch tensor.
* [`torch.Tensor.numpy()`](https://pytorch.org/docs/stable/generated/torch.Tensor.numpy.html) - PyTorch tensor -> NumPy array.

Let's try them out.



In [526]:
# Import librarys we need
import torch
import numpy as np

# Create a numpy array
exNp1 = np.arange(1.0,8.0)

# Create a tensor with numpy
exXNp1 = torch.from_numpy(exNp1)

print(f"NumPy look: \n{exNp1}\nTensor look: \n{exXNp1}")


NumPy look: 
[1. 2. 3. 4. 5. 6. 7.]
Tensor look: 
tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


> **Note:** By default, NumPy arrays are created with the datatype `float64` and if you convert it to a PyTorch tensor, it'll keep the same datatype (as above).
>
> However, many PyTorch calculations default to using `float32`.
>
> So if you want to convert your NumPy array (float64) -> PyTorch tensor (float64) -> PyTorch tensor (float32), you can use `tensor = torch.from_numpy(array).type(torch.float32)`.


In [527]:
# Get a data type of tensor we pass data from numpy array
exXNp1.dtype

torch.float64

In [528]:
# change the type of tensor to the defult of tensor
exXNp1 = exXNp1.type(torch.float32)

In [529]:
exXNp1.dtype

torch.float32

In [530]:
# Change the array, keep the tensor
exNp1 = exNp1 + 1
exNp1, exXNp1

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

And if you want to go from PyTorch tensor to NumPy array, you can call `<....>.numpy()`.

In [531]:
# Create a Tensor
exX6 = torch.arange(1,11,2)
exNp1X6 = exX6.numpy()
exX6, exNp1X6

(tensor([1, 3, 5, 7, 9]), array([1, 3, 5, 7, 9]))

## Reproducibility (trying to take the random out of random)

As you learn more about neural networks and machine learning, you'll start to discover how much randomness plays a part.

Well, pseudorandomness that is. Because after all, as they're designed, a computer is fundamentally deterministic (each step is predictable) so the randomness they create are simulated randomness (though there is debate on this too, but since I'm not a computer scientist, I'll let you find out more yourself).

How does this relate to neural networks and deep learning then?

We've discussed neural networks start with random numbers to describe patterns in data (these numbers are poor descriptions) and try to improve those random numbers using tensor operations (and a few other things we haven't discussed yet) to better describe patterns in data.

In short:

``start with random numbers -> tensor operations -> try to make better (again and again and again)``

Although randomness is nice and powerful, sometimes you'd like there to be a little less randomness.

Why?

So you can perform repeatable experiments.

For example, you create an algorithm capable of achieving X performance.

And then your friend tries it out to verify you're not crazy.

How could they do such a thing?

That's where **reproducibility** comes in.

In other words, can you get the same (or very similar) results on your computer running the same code as I get on mine?

Let's see a brief example of reproducibility in PyTorch.

We'll start by creating two random tensors, since they're random, you'd expect them to be different right?

In [532]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.0014, 0.1469, 0.5659, 0.6317],
        [0.9060, 0.9766, 0.0764, 0.1981],
        [0.9471, 0.9677, 0.2827, 0.3607]])

Tensor B:
tensor([[0.7293, 0.9291, 0.3356, 0.2807],
        [0.6151, 0.6254, 0.2654, 0.7374],
        [0.7205, 0.0366, 0.8310, 0.1095]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

Just as you might've expected, the tensors come out with different values.

But what if you wanted to create two random tensors with the *same* values.

As in, the tensors would still contain random values but they would be of the same flavour.

That's where [`torch.manual_seed(seed)`](https://pytorch.org/docs/stable/generated/torch.manual_seed.html) comes in, where `seed` is an integer (like `42` but it could be anything) that flavours the randomness.

In [533]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

## Running tensors on GPUs (and making faster computations)

Deep learning algorithms require a lot of numerical operations.

And by default these operations are often done on a CPU (computer processing unit).

However, there's another common piece of hardware called a GPU (graphics processing unit), which is often much faster at performing the specific types of operations neural networks need (matrix multiplications) than CPUs.

Your computer might have one.

If so, you should look to use it whenever you can to train neural networks because chances are it'll speed up the training time dramatically.

There are a few ways to first get access to a GPU and secondly get PyTorch to use the GPU.

> **Note:** When I reference "GPU" throughout this course, I'm referencing a [Nvidia GPU with CUDA](https://developer.nvidia.com/cuda-gpus) enabled (CUDA is a computing platform and API that helps allow GPUs be used for general purpose computing & not just graphics) unless otherwise specified.


### 1. Getting a GPU

You may already know what's going on when I say GPU. But if not, there are a few ways to get access to one.

| **Method** | **Difficulty to setup** | **Pros** | **Cons** | **How to setup** |
| ----- | ----- | ----- | ----- | ----- |
| Google Colab | Easy | Free to use, almost zero setup required, can share work with others as easy as a link | Doesn't save your data outputs, limited compute, subject to timeouts | [Follow the Google Colab Guide](https://colab.research.google.com/notebooks/gpu.ipynb) |
| Use your own | Medium | Run everything locally on your own machine | GPUs aren't free, require upfront cost | Follow the [PyTorch installation guidelines](https://pytorch.org/get-started/locally/) |
| Cloud computing (AWS, GCP, Azure) | Medium-Hard | Small upfront cost, access to almost infinite compute | Can get expensive if running continually, takes some time to setup right | Follow the [PyTorch installation guidelines](https://pytorch.org/get-started/cloud-partners/) |

There are more options for using GPUs but the above three will suffice for now.

Personally, I use a combination of Google Colab and my own personal computer for small scale experiments (and creating this course) and go to cloud resources when I need more compute power.

> **Resource:** If you're looking to purchase a GPU of your own but not sure what to get, [Tim Dettmers has an excellent guide](https://timdettmers.com/2020/09/07/which-gpu-for-deep-learning/).

To check if you've got access to a Nvidia GPU, you can run `!nvidia-smi` where the `!` (also called bang) means "run this on the command line".


In [534]:
!nvidia-smi

Thu Oct 30 16:02:35 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   50C    P0             26W /   70W |     104MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [535]:
# Check for GPU
import torch
torch.cuda.is_available()

True

If the above outputs `True`, PyTorch can see and use the GPU, if it outputs `False`, it can't see the GPU and in that case, you'll have to go back through the installation steps.

Now, let's say you wanted to setup your code so it ran on CPU *or* the GPU if it was available.

That way, if you or someone decides to run your code, it'll work regardless of the computing device they're using.

Let's create a `device` variable to store what kind of device is available.

In [536]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

If the above output `"cuda"` it means we can set all of our PyTorch code to use the available CUDA device (a GPU) and if it output `"cpu"`, our PyTorch code will stick with the CPU.

> **Note:** In PyTorch, it's best practice to write [**device agnostic code**](https://pytorch.org/docs/master/notes/cuda.html#device-agnostic-code). This means code that'll run on CPU (always available) or GPU (if available).

If you want to do faster computing you can use a GPU but if you want to do *much* faster computing, you can use multiple GPUs.

You can count the number of GPUs PyTorch has access to using [`torch.cuda.device_count()`](https://pytorch.org/docs/stable/generated/torch.cuda.device_count.html#torch.cuda.device_count).

In [537]:
# Count number of devices
torch.cuda.device_count()

1

Knowing the number of GPUs PyTorch has access to is helpful incase you wanted to run a specific process on one GPU and another process on another (PyTorch also has features to let you run a process across *all* GPUs).

### 2.1 Getting PyTorch to run on Apple Silicon

In order to run PyTorch on Apple's M1/M2/M3/M4 GPUs you can use the [`torch.backends.mps`](https://pytorch.org/docs/stable/notes/mps.html) module.

Be sure that the versions of the macOS and Pytorch are updated.

You can test if PyTorch has access to a GPU using `torch.backends.mps.is_available()`.

In [538]:
if torch.cuda.is_available():
    device = "cuda" # Use NVIDIA GPU (if available)
elif torch.backends.mps.is_available():
    device = "mps" # Use Apple Silicon GPU (if available)
else:
    device = "cpu" # Default to CPU if no GPU is available
device

'cuda'

### 3. Putting tensors (and models) on the GPU

You can put tensors (and models, we'll see this later) on a specific device by calling [`to(device)`](https://pytorch.org/docs/stable/generated/torch.Tensor.to.html) on them. Where `device` is the target device you'd like the tensor (or model) to go to.

Why do this?

GPUs offer far faster numerical computing than CPUs do and if a GPU isn't available, because of our **device agnostic code** (see above), it'll run on the CPU.

> **Note:** Putting a tensor on GPU using `to(device)` (e.g. `some_tensor.to(device)`) returns a copy of that tensor, e.g. the same tensor will be on CPU and GPU. To overwrite tensors, reassign them:
>
> `some_tensor = some_tensor.to(device)`

Let's try creating a tensor and putting it on the GPU (if it's available).

In [539]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

What if we wanted to move the tensor back to CPU?

For example, you'll want to do this if you want to interact with your tensors with NumPy (NumPy does not leverage the GPU).

Instead, to get a tensor back to CPU and usable with NumPy we can use [`Tensor.cpu()`](https://pytorch.org/docs/stable/generated/torch.Tensor.cpu.html).

This copies the tensor to CPU memory so it's usable with CPUs.

In [540]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

The above returns a copy of the GPU tensor in CPU memory so the original tensor is still on GPU.