In [ ]:
!nvidia-smi

Thu Jul 31 10:17:35 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   40C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [1]:
import torch

In [2]:
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors
Creating Tensors

Scalers are linear (or more precisely affine) transformers and differ from each other in the way they estimate the parameters used to shift and scale each feature. QuantileTransformer provides non-linear transformations in which distances between marginal outliers and inliers are shrunk.

PyTorch tensors are created usin torch.Tensor()

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [6]:
# Get tensor back as python int
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [11]:
# Matrix
Matrix = torch.tensor([[7,8],[9,10]])
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
Matrix.ndim

2

In [14]:
Matrix.size()

torch.Size([2, 2])

In [15]:
Matrix.shape

torch.Size([2, 2])

In [16]:
type(Matrix)

torch.Tensor

In [17]:
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [18]:
Matrix[0]

tensor([7, 8])

In [19]:
Matrix[1]

tensor([ 9, 10])

In [20]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [21]:
TENSOR.ndim

3

In [22]:
TENSOR.shape

torch.Size([1, 3, 3])

In [23]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [26]:
TENSOR[0][0]

tensor([1, 2, 3])

In [27]:
TENSOR[0][2]

tensor([2, 4, 5])

In [28]:
TENSOR[0][1][1]

tensor(6)